### ISSUE TITLE
Gradle Build issue

### ISSUE THREAD

**Issue by ympondaven** [walt-id/waltid-walletkit#126]
Hello, I've try  gradle build      
and get this result on a Mac OS Ventura 13 , openjdk 11, any idea of what's wrong ? 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':distTar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sub:download_repositories).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 558ms

**Comment by waltkb** [comment]
Java 11 is not supported (a lot of cryptography from JDK 15 is required for example), please update to the latest LTS version (JDK 17.0.6) or the newest version (19.0.2 or 20 GA).

You can download a modern JDK like Eclipe Temurin here https://adoptium.net/temurin/releases/?version=17 (select Operating System macOS).
