### ISSUE TITLE
Missing mandatory parameters in swagger

### ISSUE THREAD

**Issue by oriana13** [walt-id/waltid-walletkit#135]
Hello waltid team! 
I am looking to have a signed participant vc returned by the wallet.
I understand it's the /api/wallet/issuance/start route that can do this. 
Only I don't know what parameter to give it to make it work... can you help me please?
@mikeplotean @severinstampler

**Comment by severinstampler** [comment]
Hi @oriana13 
The api endpoint you're referring to, is used by the web wallet to trigger an issuance flow with an external issuer, following the OIDC for credential issuance protocol.
If you want to directly issue a signed credential, you could look into the issuer api of the walletkit.
You find a documentation of it here: https://docs.walt.id/v/web-wallet/getting-started/rest-apis/credential-issuance
Let me know if this helps, or if I misunderstood your use case.
Thanks. Best regards.
