### ISSUE TITLE
Front authentication

### ISSUE THREAD

**Issue by vgonisanz** [walt-id/waltid-walletkit#148]
The architecture of the project is very interesting. I have a question.

- How do you think is the best way to authenticate front users with the backend service?

**Comment by mikeplotean** [comment]
Hi, could you please elaborate on your question, what type of authentication do you have in mind?
- issuer-authentication - is out of scope for walletkit
- user-authentication - is handled by the [waltid-web-wallet](https://github.com/walt-id/waltid-web-wallet)

**Comment by vgonisanz** [comment]
I am analyzing ways to authenticate users, using, for example, OpenID Connect (OIDC).

I understand that the 'waltid-web-wallet' project has a basic implementation, and I was looking for guides or diagrams to properly implement authentication with a service that uses the 'wallet-kit' in the backend to utilize VC (Verifiable Credentials) and the functionalities offered by the kit.

I would also like to know if you have any plans to work on a similar line of understanding and solving this problem properly.
If not, I can try to study the standard and look into the implementation of 'waltid-web-wallet' to attempt it on my own.

Thank you.

**Comment by mikeplotean** [comment]
perhaps these 2 can help:
- [issuer-portal](https://issuer.walt.id) - https://github.com/walt-id/waltid-issuer-portal
- [verifier-portal](https://verifier.walt.id) - https://github.com/walt-id/waltid-verifier-portal

A small diagram showing the component architecture can be found on the [Issuer and Verifier portals](https://docs.walt.id/v/web-wallet/wallet-kit/issuer-and-verifier-portals) page. Also there can be found the [oidc protocol](https://docs.walt.id/v/web-wallet/concepts/oidc) description. Please keep in mind, the current oidc implementations (oidc4ci and oidc4vp) are being updated to the latest spec (oid4vc).
