### ISSUE TITLE
Bug - Endpoint /config/did/delete doesn't work

### ISSUE THREAD

**Issue by Happy2C0de** [walt-id/waltid-walletkit#164]
Hi all

First of all, very great repository and interesting project! 👏 👍 

Testing the API, I couldn't delete any created DID using the `/issuer-api/` endpoint.
I think there is a bug in the following line: [IssuerController.kt#L79](https://github.com/walt-id/waltid-walletkit/blob/cde4692cfaafc846b80cb81363ea08ba678e6ae3/src/main/kotlin/id/walt/issuer/backend/IssuerController.kt#L79C33-L79C33)

Shouldn't it be as follows:
```java
get("{id}", documented(DidController.loadDocs().describeTenantId(), DidController::load))
delete("{id}", documented(DidController.deleteDocs().describeTenantId(), DidController::delete))
```
I added the `load` functionality to extend the endpoint group.

**Comment by cre8** [comment]
I think it's the same for Key Management, the `id` of the object is also missing there

**Comment by mikeplotean** [comment]
fixed by https://github.com/walt-id/waltid-walletkit/pull/174
