### ISSUE TITLE
Bug - Endpoint for /config/did/{id} does not exist

### ISSUE THREAD

**Issue by cre8** [walt-id/waltid-walletkit#171]
Since we can not query the `/api/wallet` directly there is no endpoint right now to request the did document via the `issuer-api`.

It would be great the query it either via GET `/config/did/{id}` or `/config/did/doc/{id}`.

The first solution would follow the typical pattern for REST APIs, but could lead to breaking systems. So the other option would be the besser way in case there will be more GET endpoints in the future.

**Comment by mikeplotean** [comment]
fixed by https://github.com/walt-id/waltid-walletkit/pull/174
