### ISSUE TITLE
Bug - Endpoint to query a credential is not configured correctly

### ISSUE THREAD

**Issue by cre8** [walt-id/waltid-walletkit#172]
To query the credential the list endpoint is used with a passed query like `/api/wallet/credentials/list?id=urn:uuid:152e6f4d-134f-4f86-8eb4-28a9b70646b5`

But this query is not documented so swagger so it's not possible to generate SDKs out of the definition:
![image](https://github.com/walt-id/waltid-walletkit/assets/4020915/8bba1db0-6d5b-4987-a33e-588cc9bacbae)

Suggestion:
- add the missing annotation
- make a new route like `api/wallet/credentials/list/{id}` to fetch it

**Comment by mikeplotean** [comment]
fixed by https://github.com/walt-id/waltid-walletkit/pull/174
