### ISSUE TITLE
exec /usr/sbin/nginx: exec format error

### ISSUE THREAD

**Issue by marinkobabic** [walt-id/waltid-walletkit#180]
Both images 

waltid/ssikit-issuer-portal:latest
https://github.com/walt-id/waltid-walletkit/blob/main/k8s/deployment-prod.yaml#L181

waltid/ssikit-verifier-portal:latest 
https://github.com/walt-id/waltid-walletkit/blob/main/k8s/deployment-prod.yaml#L145

when running on kubernets are having the issue

`exec /usr/sbin/nginx: exec format error`

You have suddenly switched the architecture from amd64 to arm64
<img width="1287" alt="image" src="https://github.com/walt-id/waltid-walletkit/assets/3265080/cddf60d7-5f06-4b12-b54e-dd84b0664cd0">

**Comment by marinkobabic** [comment]
Any feedback about the time line when do you expect it to get fixed would be great.

**Comment by mikeplotean** [comment]
@marinkobabic , should be fixed now.

**Comment by marinkobabic** [comment]
Works fine, many thx :-)
