### ISSUE TITLE
docker compose woes

### ISSUE THREAD

**Issue by pohutukawa** [walt-id/waltid-walletkit#181]
I've just wanted to give WalletKit a test drive and was attempting to use the Docker Compose based deployment locally. doing so, I have caught a few glitches I wanted to report. Maybe some of it will also be helpful going forward towards using Community Stack in the future, too.

* Initial `docker compose` run complained about `extra_hosts` needing to be a mapping. To change it from a list/array to a mapping, I have just replaced the dash of the line with the host by `foo:`. I don't know whether that's broken something, but at least `docker compose` has moved forward.
* Next I got complaints about no images being available for the `arm64` architecture (on an Apple M silicone Mac). Adding a line `platform: linux/x86_64` after each `waltid` service (that's all but the `nginx` one) has resolved that problem to fire it up.
* Still getting a lot of messages in the console from one of the services: `walletkit-1    | [Too many errors, abort]`, but the rest of them seem to be working/running, when using the web interface, I'm getting a lot of log messages for them.

So, it's running now (barring the last point above), but trying to use it fails when trying either the 'Sign up' or 'Login'. Both of them are performing a `POST` request against `http://localhost:8080/api/auth/login`, causing a 502 Bad Gateway response. I'm unsure whether that may be due to the `walletkit-1` container not running properly.

I'll also get in touch with Walt.id soon directly to inquire on the use of your components in general, and potentially future services we may be interested in consuming from Walt.id.

Thanks in advance.

**Comment by cpatsonakis** [comment]
Hello!

Thank you for your interest in our stack first of all. Next, as stated in the repository's README: 
_Please be informed that, beginning from December 2023, the Wallet Kit will no longer receive new features. Furthermore, the Wallet Kit is planned for discontinuation by the end of Q3 2024.
However, all functionalities offered by the Wallet Kit are now integrated into our new libraries, APIs, and apps in the walt.id [identity repo](https://github.com/walt-id/waltid-identity). Giving you more modularity, flexibility and ease-of-use to build end-to-end digital identity and wallet solutions._

For more up-to-date developments, please refer to our community stack repo as the development of this repository has been discontinued.

Thanks again and hope to hear more from you soon!
