### ISSUE TITLE
Document SIOPv2 request how to request multiple VCs within one VP

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-walletkit#22]
How do we need to setup a presentation request for multiple credentials (SIOPv2 flow) - e.g. present your ParticipantCredential as well as a GaiaXProviderCredential for example in one presentation. Currently we have the following request:
const baseUri = 'https://wallet.lab.gaia-x.eu/verifier-api'
const schemaUri = 'https://raw.githubusercontent.com/walt-id/waltid-ssikit-vclib/master/src/test/resources/schemas/ParticipantCredential.json'
const url = `${baseURI}/present?walletId=walt.id&schemaUri=${schemaUri}`

The documentation should be updated here https://doc.walt.id/v/web-wallet/concepts/oidc/oidc-1

**Comment by severinstampler** [comment]
added possibility to specify multiple schemaId params to /present request in verifier API

**Comment by philpotisk** [comment]
@severinstampler this is great. thx! can you please also add an example request here? https://doc.walt.id/v/web-wallet/concepts/oidc/oidc-1
