### ISSUE TITLE
libsodium.so for armv6

### ISSUE THREAD

**Issue by Nabil-oussa** [walt-id/waltid-walletkit#43]
Hi team,
testing walitid-walletkit by using  docker-compose, in authentification step I have a problem with this message: "Caused by: java.lang.UnsatisfiedLinkError: Unable to load library '/tmp/resource-loader10237632198594109884/armv6/libsodium.so':". Any help, thanks in advance.

**Comment by waltkb** [comment]
Related to https://github.com/terl/lazysodium-java/issues/115

**Comment by waltkb** [comment]
I've updated the lazysodium version in the SSI Kit and included the new SSI Kit version in the Wallet Kit. Should be fixed now.
