### ISSUE TITLE
Build error | 1 Test Fails

### ISSUE THREAD

**Issue by taminobaumann** [walt-id/waltid-walletkit#90]
![Markup on 2023-01-20 at 12:14:20](https://user-images.githubusercontent.com/48290617/213682451-bed38c89-18ff-4ca8-8a8a-42d0276fe314.png)

**Comment by severinstampler** [comment]
@taminobaumann 
Please try again with --refresh-dependencies
I think the ssikit needs to be updated on your local repo cache.
br

**Comment by waltkb** [comment]
All tests are passing as of the current commit.
